# Generated by Django 5.2.4 on 2025-08-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_outfit_outfititem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfititem',
            name='default_size',
        ),
    ]
