# Generated by Django 5.2.4 on 2025-08-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_model_image',
            field=models.ImageField(blank=True, null=True, upload_to='tryon_models/'),
        ),
    ]
