# Generated by Django 5.2.4 on 2025-08-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_category_default_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='model_dress',
            field=models.ImageField(blank=True, null=True, upload_to='tryon_models/'),
        ),
        migrations.AddField(
            model_name='category',
            name='model_lower',
            field=models.ImageField(blank=True, null=True, upload_to='tryon_models/'),
        ),
        migrations.AddField(
            model_name='category',
            name='model_upper',
            field=models.ImageField(blank=True, null=True, upload_to='tryon_models/'),
        ),
        migrations.AddField(
            model_name='category',
            name='tryon_slot',
            field=models.CharField(choices=[('upper', 'Upper (tops)'), ('lower', 'Lower (bottoms)'), ('dress', 'One-piece (dress)')], default='upper', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='tryon_slot',
            field=models.CharField(blank=True, choices=[('upper', 'Upper (tops)'), ('lower', 'Lower (bottoms)'), ('dress', 'One-piece (dress)')], help_text='Override category slot for Try-On if needed.', max_length=10, null=True),
        ),
    ]
