# Generated by Django 5.2.4 on 2025-08-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_category_model_dress_category_model_lower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='default_model_image',
        ),
    ]
