# Generated by Django 5.2.4 on 2025-08-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_category_default_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tryon_slot',
            field=models.CharField(blank=True, choices=[('upper', 'Upper (tops)'), ('lower', 'Lower (bottoms)'), ('dress', 'One-piece (dress)')], max_length=10, null=True),
        ),
    ]
