# Generated by Django 5.2.4 on 2025-08-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_category_tryon_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tryon_image',
            field=models.ImageField(blank=True, help_text='Cutout PNG (transparent background) for Virtual Try‑On', null=True, upload_to='products/tryon/'),
        ),
    ]
