# Generated by Django 5.2.4 on 2025-08-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_tryon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='model_dress',
        ),
        migrations.RemoveField(
            model_name='category',
            name='model_lower',
        ),
        migrations.RemoveField(
            model_name='category',
            name='model_upper',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tryon_slot',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tryon_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tryon_slot',
        ),
    ]
