# Generated by Django 5.2.3 on 2025-09-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_category_model_dress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='title_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_bg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='content_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='title_bg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='name_bg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='name_en',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
